services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - NODE_ENV=development
      - ENABLE_MAP_FEATURES=${ENABLE_MAP_FEATURES:-true}
      - ENABLE_AI_FEATURES=${ENABLE_AI_FEATURES:-true}
    networks:
      - app_network

  prod:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - ENABLE_MAP_FEATURES=${ENABLE_MAP_FEATURES:-true}
      - ENABLE_AI_FEATURES=${ENABLE_AI_FEATURES:-true}
    networks:
      - app_network
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SERVICE_ROLE_SECRET=${SERVICE_ROLE_SECRET}
    networks:
      - app_network
    depends_on:
      - web

networks:
  app_network:
    driver: bridge 