FROM mcr.microsoft.com/playwright:v1.42.1-jammy

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source
COPY . .

# Install Playwright browsers
RUN npx playwright install chromium

# Command to run tests
CMD ["npm", "test"] 